name: Automate project columns

on: [issues, pull_request]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues into Triage
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@v0.0.3
        with:
          project: testproject
          column: To do
          repo-token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Move assinged pull requests into To do
        if: github.event_name == 'pull_request' && github.event.action == 'assigned'
        uses: alex-page/github-project-automation-plus@v0.0.3
        with:
          project: Test project
          column: To do
          repo-token: ${{ secrets.GH_ACTIONS_TOKEN }}
